services:
  discountmate:
    image: ${IMAGE}
    container_name: discountmate
    ports:
      - "${APP_PORT:-8088}:8080"
    environment:
      - PORT=8080
    profiles: ["staging"]
    restart: unless-stopped