services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/alert.rules.yml:/etc/prometheus/alert.rules.yml:ro
    command: ["--config.file=/etc/prometheus/prometheus.yml"]
    ports: ["9090:9090"]
    profiles: ["monitoring","staging","prod"]
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    ports: ["9093:9093"]
    profiles: ["monitoring","staging","prod"]
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports: ["3000:3000"]
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    profiles: ["monitoring","staging","prod"]
    restart: unless-stopped

  discountmate:
    image: ${IMAGE}
    container_name: discountmate
    ports:
      - "${APP_PORT:-8081}:8080"
    env_file:
      - ${ENV_FILE}
    restart: unless-stopped
    profiles: ["staging","prod"]
