# (optional) remove the 'version:' key to avoid the compose warning
# version: "3.9"

networks:
  dmnet:
    external: true
    name: discountmate_default   # must already exist (prod compose creates it)

services:
  prom:
    image: prom/prometheus:v2.54.1
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-lifecycle
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/alert.rules.yml:/etc/prometheus/alert.rules.yml:ro
    ports:
      - "9090:9090"                 # keep fixed for the UI
    depends_on: [blackbox, alerts]
    networks: [dmnet]

  blackbox:
    image: prom/blackbox-exporter:v0.25.0
    command: ["--config.file=/etc/blackbox_exporter/config.yml"]
    volumes:
      - ./monitoring/blackbox.yml:/etc/blackbox_exporter/config.yml:ro
    # Do NOT publish a host port; Prom scrapes via the Docker network
    networks: [dmnet]

  alerts:
    image: prom/alertmanager:v0.28.1
    command: ["--config.file=/etc/alertmanager/alertmanager.yml"]
    volumes:
      - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    # Publish Alertmanager on a random free host port to avoid 9093 clashes
    ports:
      - target: 9093
        published: ${ALERTMGR_PORT:-0}   # set ALERTMGR_PORT=9094 if you want a fixed host port
        protocol: tcp
    networks: [dmnet]