services:
  blackbox:
    image: prom/blackbox-exporter:latest
    container_name: dm_blackbox
    profiles: ["monitoring"]
    command: ["--config.file=/config/blackbox.yml"]
    volumes:
      - ./monitoring/blackbox.yml:/config/blackbox.yml:ro
    ports: ["9115:9115"]

  prometheus:
    image: prom/prometheus:latest
    container_name: dm_prom
    profiles: ["monitoring"]
    command: ["--config.file=/etc/prometheus/prometheus.yml", "--web.enable-lifecycle", "--web.enable-admin-api"]
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/alert.rules.yml:/etc/prometheus/alert.rules.yml:ro
    ports: ["9090:9090"]
    depends_on: [blackbox]

  alertmanager:
    image: prom/alertmanager:latest
    container_name: dm_alerts
    profiles: ["monitoring"]
    volumes:
      - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    ports: ["9093:9093"]