version: "3.9"

networks:
  dmnet:
    external: true
    name: discountmate_default

services:
  prom:
    image: prom/prometheus:v2.54.1
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-lifecycle
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/alert.rules.yml:/etc/prometheus/alert.rules.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - blackbox
      - alerts
    networks: [dmnet]

  blackbox:
    image: prom/blackbox-exporter:v0.25.0
    command: ["--config.file=/etc/blackbox_exporter/config.yml"]
    volumes:
      - ./monitoring/blackbox.yml:/etc/blackbox_exporter/config.yml:ro
    # IMPORTANT: do NOT publish 9115 to host; Prom talks over dmnet
    networks: [dmnet]

  alerts:
    image: prom/alertmanager:v0.28.1
    command: ["--config.file=/etc/alertmanager/alertmanager.yml"]
    volumes:
      - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    ports:
      - target: 9093
        published: ${ALERTMGR_PORT:-0}   # 0 => random free host port
        protocol: tcp
        mode: host
    networks: [dmnet]