global:
  scrape_interval: 5s
rule_files:
  - /etc/prometheus/alert.rules.yml

scrape_configs:
  # Scrape the FastAPI app via the Mac host port (works even if the app isn't on the compose network)
  - job_name: "discountmate"
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8081"]

  # Scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
