global:
  scrape_interval: 5s

rule_files:
  - /etc/prometheus/alert.rules.yml

scrape_configs:
  - job_name: 'discountmate'
    metrics_path: /metrics
    static_configs:
      - targets: ['discountmate:8080']